// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdjxmlgvfcacszpcsjuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkanhtbGd2ZmNhY3N6cGNzanVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMzYzNzgsImV4cCI6MjA1MzgxMjM3OH0.3248jJ-JSFYdw_CRjXe7ZsQxH3Ya9pYx3QFITWuVdT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);